version: '3'

services:
  client:
    build: ./client
    container_name: peerprep_client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    env_file:
      - ./client/.env.local
    environment:
      ENV: DOCKER

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  user_service_mongo_db:
    image: mongo:latest
    container_name: user_service_database
    restart: always
    volumes:
      - user_service_mongo_db:/data/db

  user_service:
    build: ./server/user-service
    container_name: user_service
    restart: always
    ports: 
      - 3001:3001
    env_file:
      - ./server/user-service/.env
    environment:
      ENV: DOCKER
    depends_on:
      - user_service_mongo_db

  question_service_mongo_db:
    image: mongo:latest
    container_name: question_service_database
    restart: always
    volumes:
      - question_service_mongo_db:/data/db

  question_service:
    build: ./server/question-service
    container_name: question_service
    restart: always
    ports: 
      - 3002:3002
    env_file:
      - ./server/question-service/.env
    environment:
      ENV: DOCKER
    depends_on:
      - question_service_mongo_db

  matching_service_mongo_db:
    image: mongo:latest
    container_name: matching_service_database
    restart: always
    volumes:
      - matching_service_mongo_db:/data/db

  matching_service:
    build: ./server/matching-service
    container_name: matching_service
    restart: always
    ports: 
      - 3003:3003
    env_file:
      - ./server/matching-service/.env
    environment:
      ENV: DOCKER
    depends_on:
      - matching_service_mongo_db
      - rabbitmq

volumes:
  user_service_mongo_db: {}
  question_service_mongo_db: {}
  matching_service_mongo_db: {}