version: '3'

services:
  user_service_mongo_db:
    image: mongo:latest
    container_name: user_service_database
    restart: always
    volumes:
      - user_service_mongo_db:/data/db

  user_service:
    build: .
    container_name: user_service
    restart: always
    ports: 
      - 3001:3001
    env_file:
      - .env
    environment:
      ENV: DOCKER
    depends_on:
      - mongo_db

volumes:
  user_service_mongo_db: {}